# Generated by Django 5.2.17 on 2026-09-24 18:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=160)),
                ("organization", models.CharField(blank=True, max_length=160)),
                (
                    "relationship_state",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("follow_up_due", "Follow-up due"),
                            ("waiting_for_reply", "Waiting for reply"),
                            ("meeting_scheduled", "Meeting scheduled"),
                            ("no_action", "No action"),
                        ],
                        default="new",
                        max_length=24,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="people",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Interaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("meeting_note", "Meeting note"),
                            ("follow_up_sent", "Follow-up sent"),
                            ("reply_received", "Reply received"),
                            ("meeting_scheduled", "Meeting scheduled"),
                            ("note", "Note"),
                        ],
                        default="meeting_note",
                        max_length=24,
                    ),
                ),
                ("occurred_at", models.DateTimeField(blank=True, null=True)),
                ("transcript", models.TextField(blank=True)),
                ("summary", models.TextField(blank=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("voice", "Voice"),
                            ("text", "Text"),
                            ("user", "User update"),
                        ],
                        default="text",
                        max_length=8,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="connections.person",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FollowUpReminder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=240)),
                ("due_at", models.DateTimeField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("snoozed", "Snoozed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="scheduled",
                        max_length=16,
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            (
                                "user_confirmed_ai_suggestion",
                                "User-confirmed suggestion",
                            ),
                        ],
                        default="user",
                        max_length=40,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "interaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reminders",
                        to="connections.interaction",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="connections.person",
                    ),
                ),
            ],
            options={
                "ordering": ["due_at", "created_at"],
            },
        ),
    ]
